server:
  port: 18081
spring:
  application:
    name: tanhua-dubbo-db
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/tanhua?userUnicode=true&characterEncodeing=utf8
    username: root
    password: 1234
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.136.160:8848
dubbo:
  registry:
    address: spring-cloud://localhost
  protocol:
    name: dubbo
    port: 20881
  scan:
    base-packages: com.tanhua.dubbo.api   #dubbo中包扫描
mybatis-plus:
  global-config:
    db-config:
      table-prefix: tb_   #表名前缀
      id-type: auto  #id策略